### PR TITLE
Updated Content-Type declarations and added new ones to cover missing file extensions.

### PR DESCRIPTION
**Pull request by fdutton**
Updated Content-Type declarations for extension-point org.eclipse.core.runtime.contentTypes.
  * Added missing file extensions
  * Changed describer to XMLRootElementContentDescriber2 from
XMLRootElementContentDescriber, which was deprecated.

### CODE REVIEW

**Comment by vazexqi** [comment]
@fdutton Thanks for the pull request. Let me take a look, test it locally and if all goes well, I'll send you a Contributor's License Agreement so that I can merge it in.

**Comment by vazexqi** [comment]
@fdutton Could you fill out at the CLA at https://github.com/forcedotcom/idecore/wiki/Contributing-Code so that we can accept your pull request? You only need to fill this form out once and we can also accept all your other pending pull requests (and any future ones after review).

**Comment by vazexqi** [comment]
@fdutton Just a ping to see if you had a chance to sign the CLA yet. I can't accept the pull request until you do. And I would very much like to accept the clean ups that you made.

**Comment by fdutton** [comment]
Hi Nicholas,

I have signed it but am reluctant to post it on the GitHub message board.
It contains my personal information. Is there a more secure address I can
use?

**Comment by fdutton** [comment]
Never mind. I found the address on the wiki page. I have sent it.

**Pull request merged**
