### PR TITLE
[issue-099] Enhance New Component Creation

### PR DESCRIPTION
**Pull request by fdutton**
Added a field for selecting a project.

image
image

### CODE REVIEW

**Comment by vazexqi** [comment]
@fdutton Thanks for the pull requests. Just wanted to let you know that I am reviewing these changes. Since it modifies quite a few files and has UI implications, it is taking a bit more time.

**Comment by fdutton** [comment]
@vazexqi 
Do you plan to merge the changes from #96, #98 or #100 into 194.eclipse? I cannot develop against the master branch now that the API version is 34 since my orgs are still at 33 (every API call fails).

What is the plan for 194.eclipse? You mentioned that you were attempting to stabilize it. Was this in anticipation of releasing it? Do you have plans for a 33.1 version? Winter '15 is a long way off.

**Comment by vazexqi** [comment]
Yes, I see the issue :-(

Originally, I wasn't planning to merge your changes into 194.eclipse since we are going to release v33 next week (barring any unusual circumstances). But, if I don't merge it into 194.eclipse you won't be able to develop against it with your current orgs, which is not ideal.

I think what I will do is release v33 next week without your changes. The reason being that we need a bit more time to create the release notes/doc – dependent on doc writer team – and it won't be in time for next week. But I don't want to delay the release.

Then, I will merge your changes in 194.eclipse so you can continue development (and create a beta version that won't have the docs). Can you elaborate on what development you plan to do so we can get an idea?

The main issue that we need to fix is to not rely on the api version number so much. There needs to be a way to have multiple WSDLs work from within a single IDE version. I don't have a good idea on how to do this yet given that the "single version per IDE" assumption is pretty baked in. Going the REST API route is not a viable solution since we lose all benefits of strong typing.

**Comment by fdutton** [comment]
I was planning to work the defect I found earlier this week (#101) but I think I may have some thoughts on how to deal with concurrent API versions.

**Pull request closed without merging**
