### PR TITLE
Issue 058

### PR DESCRIPTION
**Pull request by fdutton**
These changes correct all of the Java and Plug-in warnings.

In general, each commit corrects a single type of warning. For example, the commit titled "Remove redundant null checks" contains only changes to remove testing a reference for null when Eclipse's Null Analysis shows that the reference cannot possibly be null at that location.

The biggest change comes from replacing actions and actionSets with commands and handlers.

### CODE REVIEW

**Comment by vazexqi** [comment]
@fdutton - Thanks for cleaning up! I'll merge this in as soon as possible. I'm in the process of branching out a proper 194.eclipse (v33) and master (v34).

**Comment by vazexqi** [comment]
@fdutton Just FYI, I'm in the process of merging this into master instead of 194.eclipse since I am stabilizing that branch. There are some compilation errors in some submodules (test and debugger) that are not externally shared (yet) so I am fixing those errors first.

**Comment by fdutton** [comment]
@vazexqi 
I understand. However, it you should be aware that the three pull-requests I submitted are not cumulative. I started each from a fresh branch of 194.eclipse so that you could evaluate each independently. If needed I can resubmit the pull-requests based on a fresh branch from master (instead of 194.eclipse) so there are fewer conflicts. Let me know if you need this.

It may help in the long run if you could describe the behavior expected from the existing test harness so that we (i.e., the contributors) can create a new test harness that does not depend on proprietary Salesforce code. I would also consider signing a non-disclosure agreement so that I could gain access to the existing test harness. Either solution would reduce the amount of work that you have to do to incorporate a change.

**Comment by vazexqi** [comment]
@fdutton I will discuss with @kaplanjosh and figure out a more sustainable long term plan concerning the tests. As you correctly surmised, to open source the tests require significant clean up (not about code structure but about potentially proprietary code and non-public APIs).

**Pull request closed without merging**
